#Ansible Playbook
- name: Deploy Web Application
  hosts: db_and_web_server1,db_and_web_server2
  tasks:
     - name: Update apt repo
       apt:
         upgrade: dist
         update_cache: yes
     - name: Install all required dependencies
       apt: 
         name: "{{ item }}"
         state: present
       with_items:
         - python
         - python-setuptools
         - python-dev
         - build-essential
         - python3-pip
     - name: Copy repo mysql
       copy: src=mysql-apt-config_0.8.30-1_all.deb dest=/tmp/mysql-apt-config_0.8.30-1_all.deb
     - name: Add specified repository into sources list
       ansible.builtin.apt_repository:
         repo: deb /tmp/mysql-apt-config_0.8.30-1_all.deb
         state: present
     - name: Install MySQL Database
       apt: 
         name: "{{ item }}"
         state: present
       with_items:
         - mysql-server
         - mysql-client

     - name: Satrt MySQL service
       service:
         name: mysql
         state: started
         enabled: yes

     - name: Create application database
       mysql_db: name=employee_db state=present

     - name: Create application DB user
       mysql_user:
         name: db_user
         password: Passw0rd
         priv: '*.*:ALL'
         state: present
         host: '%'

     - name: Install python flask dependencies
       pip:
         name: "{{ item }}"
         state: present
       with_items:
         - flask
         - flask-mysql

     - name: Copy web-server code
       copy: src=app.py dest=/opt/app.py

     - name: Start web-server
       shell: FLASK_APP=app.py nohup flask run --host=0.0.0.0 &
